image:
  file: .gitpod.Dockerfile

tasks: 
    - command:
      psql -h localhost -d postgres 
      echo "CREATE DATABASE airflow_db;"
      echo "CREATE USER airflow_user WITH PASSWORD 'airflow_pass';"
      echo "GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow_user;"
      
    - command:
      airflow db init 
      
      airflow users create \
      --username admin \
      --firstname takeoff \
      --lastname institute \
      --role Admin \
      --password PASSWORD \
      --email smillslagle@gmail.com

      airflow webserver --port 8080

      airflow scheduler

ports:
  - name: Airflow UI
    description: The Airflow UI
    port: 8080
    onOpen: open-browser
