image:
  file: .gitpod.Dockerfile

tasks: 
    - command: airflow db init \
    airflow webserver --port 8080
      
#       airflow users create \
#       --username admin \
#       --firstname takeoff \
#       --lastname institute \
#       --role Admin \
#       --password PASSWORD \
#       --email smillslagle@gmail.com

#       airflow scheduler

ports:
  - name: Airflow UI
    description: The Airflow UI
    port: 8080
    onOpen: open-browser
