image:
  file: .gitpod.Dockerfile

tasks:
  - before: export AIRFLOW_HOME=/workspace/takeoff-institute-2022/airflow
  - init:
      pg start
      
  - command:
      airflow db init \
      airflow users create \
      --username admin \
      --firstname takeoff \
      --lastname institute \
      --role Admin \
      --password PASSWORD \
      --email smillslagle@gmail.com

      airflow webserver --port 8080

      airflow scheduler

ports:
  - name: Airflow UI
    description: The Airflow UI
    port: 8080
    onOpen: open-browser
