image:
  file: .gitpod.Dockerfile

tasks: 
  - command:
      psql -h localhost -d postgres \
      CREATE DATABASE airflow_db;
      CREATE USER airflow_user WITH PASSWORD 'airflow_pass';
      GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow_user;
      echo \l
      
    - command:
      airflow db init 
      
      airflow users create \
      --username admin \
      --firstname takeoff \
      --lastname institute \
      --role Admin \
      --password PASSWORD \
      --email smillslagle@gmail.com

      airflow webserver --port 8080

      airflow scheduler

ports:
  - name: Airflow UI
    description: The Airflow UI
    port: 8080
    onOpen: open-browser
