image:
  file: .gitpod.Dockerfile

tasks:
  - before: export AIRFLOW_HOME=~/airflow
  - command:
      airflow db init

      airflow users create \
      --username admin \
      --firstname airflow \
      --lastname airflow \
      --role Admin \

      airflow webserver --port 8080

      airflow scheduler
